#!/bin/bash
VDELIHOME="_VDELIHOME_"
source $VDELIHOME/.env/bin/activate
cd $VDELIHOME/cdnmanager/ftpserver

case "$1" in
	start)
		./ftpserver.py start
        	;;
	stop)
		./ftpserver.py stop
        	;;
	restart)
		./ftpserver.py restart
		;;
	status)
		./ftpserver.py status
		;;
	debug)
                # ftpserver is not meant to be called with debug from this script
		./ftpserver.py --debug
		;;

	*)
		echo "ftpserver [start|stop|restart|status|debug]"
esac
